spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/auth/**,/.well-known/jwks.json
        - id: profile-service
          uri: ${PROFILE_SERVICE_URL}
          predicates:
            - Path=/profiles/**,/me/profile/**

beamcard:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

eureka:
  client:
    enabled: false
